//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EventListenerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EventListener), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("OnBeginDrag", OnBeginDrag);
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("OnEndDrag", OnEndDrag);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("setClickHandler", setClickHandler);
		L.RegFunction("setBeginDragHandler", setBeginDragHandler);
		L.RegFunction("setDragHandler", setDragHandler);
		L.RegFunction("setEndDragHandler", setEndDragHandler);
		L.RegFunction("setUseAnim", setUseAnim);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBeginDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnBeginDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEndDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnEndDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setClickHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			System.Action<UnityEngine.EventSystems.PointerEventData> arg0 = (System.Action<UnityEngine.EventSystems.PointerEventData>)ToLua.CheckDelegate<System.Action<UnityEngine.EventSystems.PointerEventData>>(L, 2);
			obj.setClickHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setBeginDragHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			System.Action<UnityEngine.EventSystems.PointerEventData> arg0 = (System.Action<UnityEngine.EventSystems.PointerEventData>)ToLua.CheckDelegate<System.Action<UnityEngine.EventSystems.PointerEventData>>(L, 2);
			obj.setBeginDragHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setDragHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			System.Action<UnityEngine.EventSystems.PointerEventData> arg0 = (System.Action<UnityEngine.EventSystems.PointerEventData>)ToLua.CheckDelegate<System.Action<UnityEngine.EventSystems.PointerEventData>>(L, 2);
			obj.setDragHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setEndDragHandler(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			System.Action<UnityEngine.EventSystems.PointerEventData> arg0 = (System.Action<UnityEngine.EventSystems.PointerEventData>)ToLua.CheckDelegate<System.Action<UnityEngine.EventSystems.PointerEventData>>(L, 2);
			obj.setEndDragHandler(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setUseAnim(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventListener obj = (EventListener)ToLua.CheckObject<EventListener>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.setUseAnim(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

